openapi: 3.0.0
info:
  title: Interview Chat API
  description: Provides API interfaces related to interview chat
  version: 1.0.0
  
tags:
  - name: Chat
    description: Interfaces related to interview chat

paths:
  /chat/start:
    post:
      tags:
        - Chat
      summary: Start Chat
      description: Start a new interview chat session and return the first question
      operationId: startChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartChatRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponseWrapper'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
  /chat/answer:
    post:
      tags:
        - Chat
      summary: Answer Question
      description: Submit the user's answer to a question and get the next question or feedback
      operationId: answerQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponseWrapper'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    StartChatRequest:
      type: object
      required:
        - user_id
        - test_id
        - job_title
      properties:
        user_id:
          type: string
          description: User ID
        test_id:
          type: string
          description: Test ID
        job_title:
          type: string
          description: Job title
        examination_points:
          type: array
          items:
            type: string
          description: List of examination points
        test_time:
          type: integer
          description: Test time (minutes)
        language:
          type: string
          description: Interview language
          default: "Chinese"
        difficulty:
          type: string
          description: Difficulty level
          enum: ["Easy", "Medium", "Hard"]
          default: "Medium"
          
    AnswerRequest:
      type: object
      required:
        - user_id
        - test_id
        - question_id
        - user_answer
      properties:
        user_id:
          type: string
          description: User ID
        test_id:
          type: string
          description: Test ID
        question_id:
          type: string
          description: Question ID
        user_answer:
          type: string
          description: User's answer content
          
    ChatResponse:
      type: object
      properties:
        chat_id:
          type: string
          description: Chat session ID
        question_id:
          type: string
          description: Current question ID
        question:
          type: string
          description: Question content
        is_finished:
          type: boolean
          description: Whether the interview is finished
        feedback:
          type: string
          description: Feedback content (provided when the interview ends)
        score:
          type: number
          format: float
          description: Score (provided when the interview ends)
          
    ChatResponseWrapper:
      type: object
      properties:
        code:
          type: string
          description: Response code, 0 indicates success
        message:
          type: string
          description: Response message
        data:
          $ref: '#/components/schemas/ChatResponse'
          
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error details